### ISSUE TITLE
T470P引导Win10蓝屏

### ISSUE THREAD

**Issue by smafaith** [evlon/t470p-oc#1]
EFI非常好用，OC引导成功，不过Win10系统没办法引导，无论是之前安装的还是后面自行安装或者是bootcamp，参考网上各种教程也都没办法实现，请问这个怎么解决

**Comment by irelandKen** [comment]
引导Win10竟然不用机器原生的UEFI引导, 你这是舍近求远呀~

**Comment by smafaith** [comment]
@irelandKen 当时是想用PD直接识别为bootcamp，从而节省一个win系统的空间，现在还是蓝屏，不过PD就识别为bootcamp了，所以也算是解决了。

**Comment by smafaith** [comment]
一个笨的解决方法是，单个（模拟MacBook Pro，机型只有单硬盘）硬盘完全安装MacOS，然后删除dsdt，这样内部硬盘不会导致bootcamp弹出错误，然后划分好bootcamp的空间，选好ISO之后，一路下一步，会重启，但引导失败，然后rufus做一个启动U盘，用U盘启动，在bootcamp的空间里面安装好系统，这时候Mac OS下PD就会显示从bootcamp设置虚拟机，虚拟机能够正常引导，共用这个系统。
